// Generated by CoffeeScript 2.4.1
(function() {
  var _, _s;

  _ = require('underscore');

  _s = require('underscore.string');

  // module export
  module.exports = function(options = {}) {
    var decodeArr, decodeHashedId, decodeObj, hashids;
    // init options
    if (options.relations == null) {
      options.relations = {};
    }
    if (options.mappings == null) {
      options.mappings = {};
    }
    // initialize hashids
    hashids = require('elib/tools/hashids')(options);
    decodeArr = function(type, arr, decode) {
      var i, len, newArr, obj;
      if (!arr || arr.length === 0) {
        return arr;
      }
      newArr = [];
      for (i = 0, len = arr.length; i < len; i++) {
        obj = arr[i];
        if (_.isArray(obj)) {
          newArr.push(decodeArr(type, obj));
        } else if (_.isObject(obj)) {
          newArr.push(decodeObj(type, obj));
        } else if (_.isString(obj) && decode) {
          newArr.push(hashids.decode(obj, type));
        } else {
          newArr.push(obj);
        }
      }
      return newArr;
    };
    decodeHashedId = function(id, type) {
      var value;
      // decode hashed id
      value = hashids.decode(id, type);
      if (id === value) {
        // undecodable if input = output
        value = null;
      }
      if ((value == null) && isNaN(id)) {
        // pass along values that are undecodable and are non-numeric
        // Notice: because isNaN returns false for strings like '84e684'
        // it may not pass along all the string values that are undecodable
        // shouldn't be a problem although
        value = id;
      }
      // decoded value
      return value;
    };
    decodeObj = function(type, obj) {
      var findRelationType, key, relationType, relations, value;
      if (options.relations[type] != null) {
        relations = options.relations[type];
      }
      // find our relation type
      findRelationType = function(key) {
        var relationKey, relationType;
        // basic mapping
        relationType = _.findKey(options.mappings, function(item) {
          return item === key;
        });
        // widen search to our type
        if ((relations != null) && (relationType == null)) {
          // figure out relations type
          relationKey = _.findKey(relations, function(item) {
            if (item === key) {
              return true;
            } else if (_.isObject(item)) {
              return item.mapping === key;
            } else if (_.has(options.mappings, item)) {
              return options.mappings[item] === key;
            } else {
              return false;
            }
          });
          // object
          if (_.isObject(relations[relationKey])) {
            return relations[relationKey].type;
          } else {
            return relations[relationKey];
          }
        } else {
          return relationType;
        }
      };
// loop object properties
      for (key in obj) {
        value = obj[key];
        // switch by type of value
        if (_.isArray(value)) {
          relationType = findRelationType(key);
          if (relationType != null) {
            obj[key] = decodeArr(relationType, value, true);
          } else {
            obj[key] = decodeArr(type, value, key === 'id');
          }
        } else if (_.isObject(value)) {
          // decode links object
          relationType = findRelationType(key);
          if (relationType != null) {
            obj[key] = decodeObj(relationType, value);
          } else {
            obj[key] = decodeObj(type, value);
          }
        } else if (key === 'id') {
          if (obj.type != null) {
            obj[key] = decodeHashedId(value, obj.type);
          } else {
            obj[key] = decodeHashedId(value, type);
          }
        } else if (_s.endsWith(key, '_id') && obj[`${key.slice(0, -3)}_type`]) {
          // generic type based mapping (e.g. remote_id / remote_type)
          relationType = _.findKey(options.mappings, function(item) {
            return item === obj[`${key.slice(0, -3)}_type`] + '_id';
          });
          // generic link found
          if (relationType != null) {
            obj[key] = decodeHashedId(value, relationType);
          } else {
            obj[key] = value;
          }
        } else if (_.isString(value)) {
          relationType = findRelationType(key);
          if (relationType != null) {
            obj[key] = decodeHashedId(value, relationType);
          }
        }
      }
      return obj;
    };
    return {
      /*
      Exported methods
      */
      paramDecode: function(req, res, next, paramValue, paramName) {
        var ref, ref1, type;
        // this will basically be called whenever a specified param is being identified
        // we will be ignoring the paramValue provided because we need the salt to figure
        // out how to decode the value

        // this type is only used if the param name is id or ids
        type = null;
        if (paramName === 'id' || paramName === 'ids') {
          type = (ref = req.route) != null ? (ref1 = ref.path) != null ? ref1.split('/')[1] : void 0 : void 0;
        } else {
          // basic mapping
          type = _.findKey(options.mappings, function(item) {
            return item === paramName;
          });
        }
        if (type) {
          // decode?
          req.params[paramName] = decodeHashedId(paramValue, type);
        }
        // proceed
        return next();
      },
      queryBodyDecode: function(req, res, next) {
        var ref, type;
        type = (ref = req.route) != null ? ref.split('/')[1] : void 0;
        req.query = decodeObj(type, req.query);
        if (req.body != null) {
          req.body = _.isArray(req.body) ? decodeArr(type, req.body) : decodeObj(type, req.body);
        }
        return next();
      }
    };
  };

}).call(this);
