// Generated by CoffeeScript 2.4.1
(function() {
  // libraries
  var _, getRawBody, typeis;

  _ = require('underscore');

  typeis = require('type-is');

  getRawBody = require('raw-body');

  // adds rawbody element to request
  module.exports = function(options) {
    if (options == null) {
      options = {};
    }
    if (options.exclude == null) {
      options.exclude = ['json', 'urlencoded', 'multipart', 'application/vnd.api+json'];
    }
    return function(req, res, next) {
      req.rawBody = null;
      if (typeis(req, options.exclude) === false) {
        return getRawBody(req, {
          length: req.headers['content-length'],
          limit: '16mb'
        }, function(err, buffer) {
          if (!err) {
            req.rawBody = buffer;
            return next();
          } else {
            return next(err);
          }
        });
      } else {
        return next();
      }
    };
  };

}).call(this);
