// Generated by CoffeeScript 2.4.1
(function() {
  var parseUrl;

  parseUrl = require('parseurl');

  module.exports = function() {
    return function(req, res, next) {
      var i, layer, len, path, ref, reqMethod;
      reqMethod = req.method.toLowerCase();
      // this is a dirty fix to figure out the matched route until we find another way
      path = parseUrl(req).pathname;
      ref = req.app._router.stack;
      for (i = 0, len = ref.length; i < len; i++) {
        layer = ref[i];
        if (layer.match(path) && (layer.route != null) && layer.route.methods[reqMethod]) {
          req.route = layer.route.path;
          break;
        }
      }
      return next();
    };
  };

}).call(this);
