// Generated by CoffeeScript 2.4.1
(function() {
  // require
  var Promise, promiseWhile;

  Promise = require('bluebird');

  // export
  module.exports = promiseWhile = function(predicate, action, value) {
    return Promise.resolve(value).then(predicate).then(function(condition) {
      if (condition) {
        return promiseWhile(predicate, action, action());
      }
    });
  };

}).call(this);
