// Generated by CoffeeScript 2.4.1
(function() {
  // require
  var error, middleware, options, resource, resources;

  error = require('elib/error');

  // related
  resource = require('./resource');

  middleware = null;

  // our resources
  resources = {};

  // bootstrap json-api
  options = {};

  module.exports.bootstrap = function(input) {
    // store options
    options = input;
    // bootstrap response
    require('elib/json-api/response')(options);
    // initialize the middleware
    return middleware = require('elib/json-api/middleware')(options);
  };

  // common middleware
  module.exports.middleware = function() {
    return middleware;
  };

  // define a type
  module.exports.define = function(type, Model) {
    // adapter known?
    //throw new error.InvalidState() unless options.adapter?

    // create resource
    return resources[type] = resource(type, Model);
  };

  // retrieve the resource
  module.exports.resource = function(type) {
    return resources[type];
  };

}).call(this);
