// Generated by CoffeeScript 2.4.1
(function() {
  // require
  var Promise, error;

  Promise = require('bluebird');

  // elib
  error = require('elib/error');

  // defines the lime resource api
  module.exports = function(type, Model) {
    return {
      retrieve: function() {
        return function(req, res, next) {
          // find by options
          return Model.findByLime(req.context, req.limeApi).then(function(rows) {
            // send rows
            res.limeSend(rows);
            // next
            return next();
          }).catch(function(err) {
            return next(err);
          });
        };
      },
      create: function() {
        return function(req, res, next) {
          return Promise.try(function() {
            var body;
            if (req.limeApi.body == null) {
              // no data
              throw new error.InvalidArgument('data is missing');
            }
            // remove id
            body = req.limeApi.body;
            if (body.id) {
              delete body.id;
            }
            // create model using the body
            return Model.create(body);
          }).then(function(row) {
            return res.limeSend(row);
          }).catch(function(err) {
            return next(err);
          });
        };
      },
      update: function() {
        return function(req, res, next) {
          return Promise.try(function() {
            var body;
            if (req.limeApi.body == null) {
              // no data
              throw new error.InvalidArgument('data is missing');
            }
            // remove id
            body = req.limeApi.body;
            if (body.id) {
              delete body.id;
            }
            // find model using the id
            return Model.findById(req.params.id).then(function(row) {
              return row.updateAttributes(body).then(function() {
                return res.limeSend(row);
              });
            });
          }).catch(function(err) {
            return next(err);
          });
        };
      },
      destroy: function() {
        return function(req, res, next) {
          return Model.findById(req.params.id).then(function(row) {
            return row.destroy().then(function() {
              return res.limeSend(row);
            });
          }).catch(function(err) {
            return next(err);
          });
        };
      }
    };
  };

}).call(this);
