// Generated by CoffeeScript 2.4.1
(function() {
  var _;

  _ = require('underscore');

  // Construct the error objects - see http://bjb.io/development/2012/05/06/an-argument-against-subclassing-error.html
  _.each(['PermissionDenied', 'Unauthorized', 'ObjectNotFound', 'InvalidArgument', 'InvalidState', 'NoContent'], function(name) {
    module.exports[name] = function(msg, details) {
      var self;
      self = new Error(msg);
      self.name = name;
      self.details = details;
      self.__proto__ = module.exports[name].prototype;
      return self;
    };
    return module.exports[name].prototype.__proto__ = Error.prototype;
  });

}).call(this);
