// Generated by CoffeeScript 2.4.1
(function() {
  var Promise, _, auth, doRequest, error, initRequest, pipe, request, rqf, serverConfig;

  Promise = require('bluebird');

  request = require('request-promise');

  rqf = require('rqf');

  _ = require('underscore');

  // server config
  serverConfig = rqf('server.config');

  // error
  error = require('elib/error');

  // authentication request
  auth = function(url, headers, body) {
    // try
    return Promise.try(function() {
      var options;
      url = `${serverConfig.server.elms}/${url}`;
      options = {
        json: true,
        url: url,
        headers: headers,
        form: body
      };
      // post request
      return request.post(options);
    });
  };

  // pipe request to elms
  pipe = function(req, res, url, access_token) {
    // try
    return Promise.try(function() {
      var elmsReq;
      // build request
      elmsReq = initRequest(url, access_token);
      // pipe request
      return req.pipe(elmsReq).pipe(res);
    });
  };

  // does a request to elms
  doRequest = function(url, options, access_token) {
    var elmsReq;
    if (options == null) {
      // init options
      options = {};
    }
    if (!_.has(options, 'json')) {
      // default to json request
      options.json = true;
    }
    // set url
    options.url = url;
    // build request
    elmsReq = initRequest(options, access_token);
    // attach headers
    return elmsReq;
  };

  // prepare a request to elms
  initRequest = function(options, access_token) {
    var elmsReq, ref;
    if (!_.isObject(options)) {
      // init options
      options = {
        url: options
      };
    }
    if (options.url != null) {
      // url given?
      options.url = `${serverConfig.server.elms}/${options.url}`;
    }
    if (((ref = options.headers) != null ? ref['accept-encoding'] : void 0) != null) {
      // remove accept encoding from headers of this request
      delete options.headers['accept-encoding'];
    }
    // locale given?
    if (options.locale != null) {
      if (options.headers == null) {
        options.headers = {};
      }
      options.headers['accept-language'] = options.locale;
      delete options.locale;
    }
    // init request
    elmsReq = request(options);
    // auth?
    if (access_token != null) {
      elmsReq = elmsReq.auth(null, null, true, access_token);
    }
    // return request
    return elmsReq;
  };

  // this is used for sending post urlencoded request
  // exports
  module.exports.auth = auth;

  module.exports.pipe = pipe;

  // export methods
  _.each(['get', 'post', 'put', 'delete'], function(method) {
    return module.exports[method] = function(url, options, access_token) {
      if (options == null) {
        // init options
        options = {};
      }
      options.method = method;
      // does the request
      return doRequest(url, options, access_token);
    };
  });

}).call(this);
