// Generated by CoffeeScript 2.4.1
(function() {
  // cursor class
  var Cursor;

  module.exports = Cursor = (function() {
    class Cursor {
      // create object
      constructor(_context) {
        this._context = _context;
        this;
      }

      // the the font and possibly the size
      setFont(_font, size) {
        this._font = _font;
        if (size != null) {
          this._size = size;
        }
        this._computeLineHeight();
        return this;
      }

      // sets the font size
      setFontSize(_size) {
        this._size = _size;
        this._computeLineHeight();
        return this;
      }

      // sets the line spacing
      setLineSpacing(spacing) {
        this._lineSpacing = spacing;
        return this;
      }

      // sets the color
      setColor(color) {
        this._color = color;
        return this;
      }

      // write a line of text
      writeText(text) {
        this._writeText(text, this._x, this._y);
        return this;
      }

      // write a line of text
      writeLine(text) {
        // write the text
        this.writeText(text);
        // increment y
        this.skipLine();
        return this;
      }

      // write many lines
      writeLines(lines) {
        var i, len, line;
        if (!Array.isArray(lines)) {
          lines = [lines];
        }
        for (i = 0, len = lines.length; i < len; i++) {
          line = lines[i];
          this.writeLine(line);
        }
        return this;
      }

      // write text in the bounding box
      writeBox(text, width, height, halign, valign) {
        var dimension, x, y;
        // compute dimension
        dimension = this._font.calculateTextDimensions(text, this._size);
        // compute missing properties
        width = width || dimension.width;
        height = height || dimension.height;
        // default position
        x = this._x;
        y = this._y;
        // horizontal alignment
        if (halign === 'center') {
          x = this._x + Math.round(width / 2) - Math.round(dimension.width / 2);
        } else if (halign === 'right') {
          x = this._x + width - dimension.width;
        }
        // vertical alignment
        if (valign === 'middle') {
          y = this._y - Math.round(height / 2) + Math.round(dimension.height / 2);
        } else if (valign === 'bottom') {
          y = this._y - height + dimension.height;
        }
        // write the text
        this._writeText(text, x, y);
        return this;
      }

      // write object specification
      writeObject(object) {
        // switch by type
        if ((object != null ? object.type : void 0) === 'image') {
          this._context.drawImage(object.x, object.y, object.file);
        } else if ((object != null ? object.type : void 0) === 'text') {
          if ((object.x != null) && (object.y != null)) {
            this._writeText(object.text, object.x, object.y);
          } else {
            this.writeLine(object.text);
          }
        }
        return this;
      }

      // write many object specifications
      writeObjects(objects) {
        var i, len, object;
        if (!Array.isArray(objects)) {
          objects = [objects];
        }
        for (i = 0, len = objects.length; i < len; i++) {
          object = objects[i];
          this.writeObject(object);
        }
        return this;
      }

      // skip a line of text
      skipLine(number = 1) {
        // increment y
        this._y -= Math.round(1000 * number * (this._lineHeight + this._lineSpacing * this._lineHeight)) / 1000;
        return this;
      }

      // get the context
      getContext() {
        return this._context;
      }

      // get the current position
      getPosition() {
        return {
          x: this._x,
          y: this._y
        };
      }

      // get x position
      getX() {
        return this._x;
      }

      // get y position
      getY() {
        return this._y;
      }

      // set a new position
      setPosition(x, y) {
        this._x = x;
        this._y = y;
        return this;
      }

      // set x
      setX(x) {
        this._x = x;
        return this;
      }

      // set y
      setY(y) {
        this._y = y;
        return this;
      }

      // move the cursor
      move(x, y) {
        this._x += x;
        this._y += y;
        return this;
      }

      // move cursor X
      moveX(x) {
        this._x += x;
        return this;
      }

      // move cursor Y
      moveY(y) {
        this._y += y;
        return this;
      }

      // gets the line height
      getLineHeight() {
        return this._lineHeight;
      }

      // write the text
      _writeText(text, x, y) {
        return this._context.writeText(text, x, y, {
          size: this._size,
          font: this._font,
          color: this._color
        });
      }

      // compute the line height
      _computeLineHeight() {
        var dimension;
        if (this._font == null) {
          return;
        }
        dimension = this._font.calculateTextDimensions('AAA', this._size);
        return this._lineHeight = dimension.height;
      }

    };

    // our properties
    Cursor.prototype._context = null;

    Cursor.prototype._x = 0;

    Cursor.prototype._y = 760; // start position

    Cursor.prototype._font = null;

    Cursor.prototype._size = 11;

    Cursor.prototype._color = 0x000000;

    Cursor.prototype._lineSpacing = 1;

    Cursor.prototype._lineHeight = 0;

    return Cursor;

  }).call(this);

}).call(this);
