// Generated by CoffeeScript 2.4.1
(function() {
  var path;

  path = require('path');

  // export
  module.exports = function(writer, config) {
    var fonts;
    fonts = {};
    // getter
    return function(font, variation) {
      var key;
      // define key
      variation = variation || 'regular';
      key = [font, variation].join('-');
      // font loaded?
      if ((fonts[key] == null) && (config.types[font][variation] != null)) {
        fonts[key] = writer.getFontForFile(path.join(config.path, config.types[font][variation]));
      }
      // return
      return fonts[key];
    };
  };

}).call(this);
