// Generated by CoffeeScript 2.4.1
(function() {
  var _;

  _ = require('underscore');

  describe('tools', function() {
    return describe('deepExtend', function() {
      var deepExtend, i, j, objs;
      // require function
      deepExtend = require('elib/tools/deepExtendClone');
      // define test objects
      objs = [];
      for (i = j = 1; j <= 3; i = ++j) {
        objs[i - 1] = {
          name: 'obj' + i,
          subobj: {
            name: 'subobj' + i
          }
        };
        objs[i - 1]['obj' + i] = 'obj' + i;
        objs[i - 1]['subobj']['subobj' + i] = 'subobj' + i;
        objs[i - 1]['subobj' + i] = _.clone(objs[i - 1]['subobj']);
      }
      it('should deep extend two objects', function() {
        var final, k, results;
        // final
        final = deepExtend(objs[0], objs[1]);
        // main elements
        expect(final.name).to.be.equal('obj2');
        expect(final.subobj.name).to.be.equal('subobj2');
// elements
        results = [];
        for (i = k = 1; k <= 2; i = ++k) {
          expect(final['obj' + i]).to.be.equal('obj' + i);
          results.push(expect(final.subobj['subobj' + i]).to.be.equal('subobj' + i));
        }
        return results;
      });
      return it('should deep extend three objects', function() {
        var final, k, results;
        // final
        final = deepExtend(objs[0], objs[1], objs[2]);
        // main elements
        expect(final.name).to.be.equal('obj3');
        expect(final.subobj.name).to.be.equal('subobj3');
// elements
        results = [];
        for (i = k = 1; k <= 3; i = ++k) {
          expect(final['obj' + i]).to.be.equal('obj' + i);
          results.push(expect(final.subobj['subobj' + i]).to.be.equal('subobj' + i));
        }
        return results;
      });
    });
  });

}).call(this);
