// Generated by CoffeeScript 2.4.1
(function() {
  var _;

  _ = require('underscore');

  describe('tools', function() {
    return describe('hashids', function() {
      var hashids;
      // initialize hashids
      hashids = require('elib/tools/hashids')({
        default: 'b589bf003b594598a5e3b9f2a3af3a5c'
      });
      it('should encode a single id', function() {
        var hashed;
        hashed = hashids.hash(1, 'default');
        return expect(hashed).to.equal('g4qg4y');
      });
      /*
       * library does not support this
      it('should encode id arrays', ->
          hashed = hashids.hash '1,2,3', 'default'
          expect(hashed).to.deep.equal ['g4qg4y', 'z42r4p', '24gx37']
      )
       */
      it('should decode a single id', function() {
        var decoded;
        decoded = hashids.decode('g4qg4y', 'default');
        return expect(decoded).to.equal(1);
      });
      it('should decode id arrays', function() {
        var decoded;
        decoded = hashids.decode('g4qg4y,z42r4p,24gx37', 'default');
        return expect(decoded).to.deep.equal([1, 2, 3]);
      });
      return it('should decode special id', function() {
        var decoded;
        decoded = hashids.decode('84e683', 'default');
        return expect(decoded).to.equal(49);
      });
    });
  });

}).call(this);
