// Generated by CoffeeScript 2.4.1
(function() {
  var Promise, _;

  _ = require('underscore');

  Promise = require('bluebird');

  describe('tools', function() {
    return describe('hostInfo', function() {
      var hostInfo;
      // require function
      hostInfo = require('elib/tools/hostInfo');
      return it('should resolve countries for ip addresses', function() {
        var map;
        if (_.contains(TEST_ENV, 'offline')) {
          // not testing if offline
          return this.skip();
        }
        // init map
        map = [['83.150.7.194', 'CH'], ['5.9.53.30', 'DE'], ['8.8.8.8', 'US']];
        // swiss ip
        return expect(Promise.each(map, function(element) {
          return hostInfo(element[0]).then(function(hostInfo) {
            return expect(hostInfo.country).to.equal(element[1]);
          });
        })).to.be.fulfilled;
      });
    });
  });

}).call(this);
