// Generated by CoffeeScript 2.4.1
(function() {
  module.exports = function(obj, path, def) {
    var i, len, p, ref;
    // define path
    path = path || '';
    ref = path.split('.');
    // loop splitted path
    for (i = 0, len = ref.length; i < len; i++) {
      p = ref[i];
      if (!obj || typeof obj !== 'object') {
        return def;
      }
      obj = obj[p];
    }
    if (obj == null) {
      // default?
      obj = def;
    }
    // return
    return obj;
  };

}).call(this);
