// Generated by CoffeeScript 2.4.1
(function() {
  var deepClone, deepExtend;

  deepClone = require('elib/tools/deepClone');

  deepExtend = require('elib/tools/deepExtend');

  // export deepExtend
  module.exports = function(destination, ...sources) {
    var i, len, source;
    for (i = 0, len = sources.length; i < len; i++) {
      source = sources[i];
      destination = deepExtend(deepClone(destination), deepClone(source));
    }
    return destination;
  };

}).call(this);
