// Generated by CoffeeScript 2.4.1
(function() {
  var _, deepExtend;

  _ = require('underscore');

  // deep extend two objects
  deepExtend = function(destination, source) {
    if (_.isObject(source)) {
      _.each(source, (value, property) => {
        if (_.has(destination, property)) {
          if (_.isObject(value) && _.isObject(destination[property])) {
            return destination[property] = deepExtend(destination[property], value);
          } else {
            return destination[property] = value;
          }
        } else {
          return destination[property] = value;
        }
      });
      // return
      return destination;
    } else {
      return source;
    }
  };

  // export deepExtend
  module.exports = function(destination, ...sources) {
    var i, len, source;
    for (i = 0, len = sources.length; i < len; i++) {
      source = sources[i];
      if (source != null) {
        destination = deepExtend(destination, source);
      }
    }
    return destination;
  };

}).call(this);
