// Generated by CoffeeScript 2.4.1
(function() {
  var _, deepClone;

  _ = require('underscore');

  // exports the deep clone
  module.exports = deepClone = function(object) {
    if (object != null) {
      return JSON.parse(JSON.stringify(object));
    }
  };

}).call(this);
