// Generated by CoffeeScript 2.4.1
(function() {
  var _, hydrate, reduce;

  _ = require('underscore');

  // hydrates a flattened object from array
  module.exports.hydrate = hydrate = function(items) {
    var current, i, leaf, len, name, obj, path, value;
    // loop objects
    obj = {};
    for (path in items) {
      value = items[path];
      path = path.split('.');
      leaf = path.pop();
      current = obj;
      for (i = 0, len = path.length; i < len; i++) {
        name = path[i];
        if (!((current[name] != null) && _.isObject(current[name]))) {
          current[name] = {};
        }
        current = current[name];
      }
      current[leaf] = value;
    }
    return obj;
  };

  // flattens an object into an array
  module.exports.reduce = reduce = function(object, path = null) {
    var key, name, obj, value;
    obj = {};
    for (key in object) {
      value = object[key];
      name = key;
      if (path != null) {
        name = [path, key].join('.');
      }
      if (_.isObject(value) && !_.isArray(value)) {
        obj = _.extend(obj, reduce(value, name));
      } else {
        obj[name] = value;
      }
    }
    return obj;
  };

}).call(this);
