// Generated by CoffeeScript 2.4.1
(function() {
  var _, generateCode;

  _ = require('underscore');

  // exports the deep extend
  module.exports = generateCode = function(length, type) {
    var chars, code, i, ints, lowers, start, uppers;
    if (length == null) {
      // define length
      length = 6;
    }
    // alphabeth
    ints = '23456789';
    uppers = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
    lowers = 'abcdefghijklmnpqrstuvwxyz';
    // chars
    chars = '';
    // by type
    start = 2;
    switch (type) {
      case 'int':
        chars += ints;
        start = 1;
        break;
      case 'lower':
        chars += lowers;
        chars += ints;
        break;
      case 'upper':
        chars += uppers;
        chars += ints;
        break;
      default:
        chars += uppers;
        chars += lowers;
        chars += ints;
    }
    // code
    code = (function() {
      var j, ref, ref1, results;
      results = [];
      for (i = j = ref = start, ref1 = length; (ref <= ref1 ? j <= ref1 : j >= ref1); i = ref <= ref1 ? ++j : --j) {
        results.push(chars.charAt(_.random(0, chars.length - 1)));
      }
      return results;
    })();
    if (type !== 'int') {
      
      // Makes sure the code starts with a character (prevents misinterpretation
      code.unshift(chars.charAt(_.random(0, chars.length - ints.length)));
    }
    // return final code
    return code.join('');
  };

}).call(this);
