// Generated by CoffeeScript 2.4.1
(function() {
  var Hashids, _, decode, encode;

  _ = require('underscore');

  Hashids = require('hashids');

  // main export
  module.exports = function(options) {
    var salts;
    // salts
    salts = (options != null ? options.salts : void 0) || options || {};
    return {
      
      // Module Methods
      hash: function(id, type) {
        if (type in salts && id) {
          return encode(id, salts[type]);
        } else {
          return id;
        }
      },
      decode: function(hashedId, type) {
        var i, len, paramVal, ref, value, values;
        if (type in salts && hashedId && _.isString(hashedId)) {
          values = [];
          ref = hashedId.split(',');
          for (i = 0, len = ref.length; i < len; i++) {
            paramVal = ref[i];
            // do not change 6 to other value. It is hardcoded because it is used to create links. If value is changed, links will be broken
            value = paramVal;
            if (paramVal.length >= 6) {
              value = decode(paramVal, salts[type]);
              if (value == null) {
                value = paramVal;
              }
            }
            values.push(value);
          }
          if (values.length > 1) {
            return values;
          } else {
            return values[0];
          }
        } else {
          return hashedId;
        }
      }
    };
  };

  // encode helper
  module.exports.encode = encode = function(id, salt) {
    var hashids;
    // id should always be a number
    id = Number(id);
    // alphabet and minhash length should never change
    hashids = new Hashids(salt, 6, 'abcdefghjklmnpqrstuvwxyz23456789');
    return hashids.encode(id);
  };

  // decode helper
  module.exports.decode = decode = function(encodedId, salt) {
    var hashids, ids;
    // alphabet and minhash length should never change
    hashids = new Hashids(salt, 6, 'abcdefghjklmnpqrstuvwxyz23456789');
    
    // hashids returns an array
    ids = hashids.decode(encodedId);
    if (ids.length > 0) {
      // let's return the first element or undefined
      return ids[0];
    }
  };

}).call(this);
