// Generated by CoffeeScript 2.4.1
(function() {
  var _, filter, find, flatten;

  _ = require('underscore');

  // find the element in the included array
  module.exports.find = find = function(arr, type, id) {
    return _.find(arr, function(element) {
      return element.type === type && element.id === id;
    });
  };

  // filter the array for the given type
  module.exports.filter = filter = function(arr, type) {
    return _.filter(arr, function(element) {
      return element.type === type;
    });
  };

  //turns {id: id, type: 'type', attributes: {}} into plain object with id and attrs. works for arrays too.
  module.exports.flatten = flatten = function(data, included = null) {
    var isArray;
    if (data == null) {
      // exclude null objects
      return null;
    }
    // single object or array?
    isArray = _.isArray(data);
    if (!isArray) {
      data = [data];
    }
    // map the data
    data = data.map(function(obj) {
      var transformed;
      // init the transformed object
      transformed = _.extend({
        id: obj.id
      }, obj.attributes);
      if (obj.relationships != null) {
        transformed = _.extend(transformed, _.mapObject(obj.relationships, function(value) {
          var isSingle;
          if ((value != null ? value.data : void 0) == null) {
            // no data in relationship
            return null;
          }
          // single relationsship
          isSingle = !_.isArray(value.data);
          if (isSingle) {
            value.data = [value.data];
          }
          // map the relationship
          value.data = value.data.map(function(rel) {
            var related;
            related = null;
            if (included != null) {
              related = find(included, rel.type, rel.id);
            }
            if (related != null) {
              return flatten(related, included);
            } else {
              return {
                id: rel.id
              };
            }
          });
          if (isSingle) {
            // return
            value.data = _.first(value.data);
          }
          return value.data;
        }));
      }
      // return
      return transformed;
    });
    if (!isArray) {
      // return
      data = _.first(data);
    }
    return data;
  };

  // create an jsonApi body using type id and data
  module.exports.body = function(type, attributes) {
    var attribute, i, isArray, len, result, results;
    // is an array?
    isArray = _.isArray(attributes);
    if (!isArray) {
      attributes = [attributes];
    }
    // init
    results = [];
// loop attributes
    for (i = 0, len = attributes.length; i < len; i++) {
      attribute = attributes[i];
      // init result
      result = {
        type: type
      };
      // move relationships
      if (attribute.relationships != null) {
        result.relationships = attribute.relationships;
        delete attribute.relationships;
      }
      // add id?
      if (_.isObject(attribute)) {
        if (attribute.id != null) {
          result.id = attribute.id;
          delete attribute.id;
        }
        result.attributes = attribute;
      } else {
        result.id = attribute;
      }
      // add to results
      results.push(result);
    }
    return {
      // return
      data: isArray ? results : _.first(results)
    };
  };

  // builds relationship body
  module.exports.relationship = function(type, ids) {
    var i, id, isArray, len, results;
    // is an array?
    isArray = _.isArray(ids);
    if (!isArray) {
      ids = [ids];
    }
    // init
    results = [];
// loop id
    for (i = 0, len = ids.length; i < len; i++) {
      id = ids[i];
      results.push({
        type: type,
        id: id
      });
    }
    return {
      // return
      data: isArray ? results : _.first(results)
    };
  };

}).call(this);
