// Generated by CoffeeScript 2.4.1
(function() {
  // require
  var _s;

  _s = require('underscore.string');

  module.exports.format = function(value) {
    return _s.sprintf('%.2f', value);
  };

  module.exports.formatAmount = function(value) {
    return Number(_s.sprintf('%.2f', value));
  };

}).call(this);
