// Generated by CoffeeScript 2.4.1
(function() {
  var Q, bcrypt, comparePasswords, generateSalt, hashPassword, rqf, serverConfig;

  bcrypt = require('bcrypt');

  Q = require('bluebird-q');

  rqf = require('rqf');

  serverConfig = rqf("server.config");

  generateSalt = function() {
    var deferred;
    deferred = Q.defer();
    bcrypt.genSalt(10, deferred.makeNodeResolver());
    return deferred.promise;
  };

  hashPassword = function(password, salt) {
    var deferred;
    deferred = Q.defer();
    bcrypt.hash(password, salt, deferred.makeNodeResolver());
    return deferred.promise;
  };

  comparePasswords = function(password, hash) {
    var deferred;
    deferred = Q.defer();
    bcrypt.compare(password, hash, deferred.makeNodeResolver());
    return deferred.promise;
  };

  exports.encryptPassword = function(password) {
    // 1- first encrypt using the server salt
    return hashPassword(password, serverConfig.server.salt).then(function(serverHashedPassword) {
      password = serverHashedPassword;
      return generateSalt();
    }).then(function(generatedSalt) {
      return hashPassword(password, generatedSalt);
    });
  };

  exports.authenticatePassword = function(password, encryptedPassword) {
    return hashPassword(password, serverConfig.server.salt).then(function(hash) {
      return comparePasswords(hash, encryptedPassword);
    });
  };

  exports.passwordIsOurs = function(encryptedPassword) {
    var e, rounds;
    try {
      rounds = bcrypt.getRounds(encryptedPassword);
      return rounds > 0;
    } catch (error) {
      e = error;
      return false;
    }
  };

}).call(this);
