// Generated by CoffeeScript 2.4.1
(function() {
  var md5;

  md5 = require('md5');

  module.exports = function(client, ns, ttl, f) {
    return function() {      // returns the function
      var args, key;
      // define key based on the function arguments
      args = Array.prototype.slice.call(arguments);
      key = ns + ':' + md5(JSON.stringify(args));
      // load from cache
      return client.get(key).then(function(data) {
        if (data) {
          return JSON.parse(data);
        } else {
          return f.apply(this, args).then(function(data) {
            // cache
            return client.setex(key, ttl, JSON.stringify(data)).then(function() {
              return data;
            });
          });
        }
      });
    };
  };

}).call(this);
