// Generated by CoffeeScript 2.4.1
(function() {
  module.exports = function(s) {
    return s.split('').reduce((function(a, b) {
      a = (a << 5) - a + b.charCodeAt(0);
      return a & a;
    }), 0) & 0x0FFFFFFF;
  };

}).call(this);
