// Generated by CoffeeScript 2.4.1
(function() {
  // i18n country and currency data module
  // extends the basic i18n functionality
  var _, cache, countryData, error, exports, getSymbol, rqf, safeAlias, vatrates;

  _ = require('underscore');

  countryData = require('country-data');

  vatrates = require('vatrates');

  getSymbol = require('currency-symbol-map');

  rqf = require('rqf');

  // tools
  safeAlias = require('elib/tools/safeAlias');

  error = require('elib/error');

  // locales
  cache = {};

  // export
  module.exports = exports = function(locale) {
    var countries, currencies, inter, languages;
    // cached?
    if (!_.has(cache, locale)) {
      // load inter
      inter = require('inter').load(locale);
      // loop countries
      countries = [];
      _.each(inter.countries, function(country) {
        var currency, ref, ref1, tax;
        // the defaults
        currency = 'EUR';
        tax = 0;
        // known country
        if (((ref = countryData.countries[country.id]) != null ? ref.currencies : void 0) != null) {
          currency = _.first(countryData.countries[country.id].currencies);
        }
        // taxable country
        if ((ref1 = country.id) === 'CH' || ref1 === 'LI') {
          tax = 8;
        } else if (vatrates[country.id] != null) {
          tax = vatrates[country.id].rates.standard;
        }
        // push to countries
        return countries.push({
          name: country.displayName,
          code: country.id,
          currency: currency,
          tax: tax
        });
      });
      // sort countries by their name
      countries.sort(function(a, b) {
        a = safeAlias.chars(a.name);
        b = safeAlias.chars(b.name);
        if (a < b) {
          return -1;
        } else if (a > b) {
          return 1;
        } else {
          return 0;
        }
      });
      // loop currencies
      currencies = [];
      _.each(inter.currencies, function(currency) {
        var symbol;
        symbol = currency.id;
        if ((getSymbol(currency.id) != null) && getSymbol(currency.id) !== '?') {
          symbol = getSymbol(currency.id);
        }
        if (currency.id === 'CHF') { // force
          symbol = 'Fr.';
        }
        return currencies.push({
          name: currency.displayName,
          code: currency.id,
          symbol: symbol
        });
      });
      // loop languages
      languages = [];
      _.each(inter.languages, function(language) {
        return languages.push({
          name: language.displayName,
          code: language.id
        });
      });
      // create i18n for locale
      cache[locale] = {
        // the locale
        locale: locale,
        // access to inter
        inter: inter,
        // the countries
        countries: countries,
        // the currencies
        currencies: currencies,
        // the languages
        languages: languages,
        // get country
        getCountry: function(code) {
          return _.find(this.countries, function(country) {
            return country.code === code;
          });
        },
        // has the country?
        hasCountry: function(code) {
          return this.getCurrency(code) !== null;
        },
        // get currency
        getCurrency: function(code) {
          return _.find(this.currencies, function(currency) {
            return currency.code === code;
          });
        },
        // has the currency?
        hasCurrency: function(code) {
          return this.getCurrency(code) !== null;
        },
        // get language
        getLanguage: function(code) {
          return _.find(this.languages, function(language) {
            return language.code === code;
          });
        },
        // has the language?
        hasLanguage: function(code) {
          return this.getLanguage(code) !== null;
        }
      };
    }
    // return
    return cache[locale];
  };

}).call(this);
