// Generated by CoffeeScript 2.4.1
(function() {
  /*
      "some_key" : [ null, "%(text)s %(keys)d key", "%(text)s %(keys)d keys" ]
      i18n.translate('some_key')
          .ifPlural(n)
          .fetch({
              keys: n
              text: 'some text'
          })
  */
  var Jed, Q, _, _s, cache, countries, country, create, error, fs, get, info, language, languages, load, locale, locales, moment, path, rqf, serverConfig, timestamp;

  // libs
  _ = require('underscore');

  _s = require('underscore.string');

  rqf = require('rqf');

  Q = require('bluebird-q');

  fs = require('q-io/fs');

  Jed = require('jed');

  path = require('path');

  moment = require('moment');

  // server config
  serverConfig = rqf('server.config');

  // error
  error = require('elib/error');

  // the timestamp
  timestamp = 0;

  // information
  info = null;

  // cached apis
  cache = {};

  // load the data
  load = function() {
    if ((info == null) || moment(info.loaded).add(1, 'minute').isBefore(new Date)) {
      return fs.read(path.join(serverConfig.translation.base, 'index.json')).then(function(content) {
        var promises;
        // promises
        promises = [];
        // parse the data
        info = JSON.parse(content);
        // remeber load time
        info.loaded = Date.now();
        // rebuild cache?
        if (info.time !== timestamp) {
          timestamp = info.time;
          _.each(info.locales, function(locale) {
            return promises.push(create(locale));
          });
        }
        // fulfill all promises
        return Q.all(promises);
      });
    }
  };

  // load locale
  get = function(locale) {
    var country, language;
    // re-load, but don't wait!
    load();
    // locale unkown
    if (!_.has(cache, locale)) {
      // split
      [language, country] = locale.split('-');
      // try default country of language
      if (_.has(serverConfig.locale.languages, language)) {
        country = serverConfig.locale.languages[language];
        locale = [language, country].join('-');
        // still no locale, first matching country of language
        if (!_.has(cache, locale)) {
          country = _.find(serverConfig.locale.languages[language], function(c) {
            return _.has(cache, [language, c].join('-'));
          });
          locale = [language, country].join('-');
        }
      }
    }
    if (!_.has(cache, locale)) {
      // unavailable
      throw new error.InvalidArgument('no and no similar locale available');
    }
    // return
    return cache[locale];
  };

  // create locale
  create = function(locale) {
    var promises;
    if (!_.contains(info.locales, locale)) {
      // valid locale
      throw new error.InvalidArgument('locale is invalid');
    }
    // init promises
    promises = [];
    _.each(info.domains, function(domain) {
      return promises.push(fs.read(path.join(serverConfig.translation.base, locale, domain + '.json')));
    });
    // build api
    return Q.all(promises).then(function(results) {
      var messages, translations;
      // init messages
      messages = {};
      // loop results
      _.each(results, function(data) {
        return messages = _.extend(messages, JSON.parse(data));
      });
      // create translations
      translations = {};
      _.each(messages, function(message, key) {
        if (!_s.endsWith(key, '_plural')) {
          translations[key] = [null, message];
          if (_.has(messages, key + '_plural')) {
            return translations[key].push(messages[key + '_plural']);
          }
        }
      });
      // add translation information
      translations[''] = {
        domain: 'messages',
        lang: locale,
        plural_forms: "nplurals=2; plural=(n != 1);"
      };
      // build the api cache and return
      cache[locale] = new Jed({
        domain: 'messages',
        locale_data: {
          messages: translations
        }
      });
      // set the used locale
      cache[locale].locale = locale;
      cache[locale].language = language(locale);
      cache[locale].country = country(locale);
      // get additional i18n data
      cache[locale].getData = function() {
        return rqf.dir(__dirname)('data')(locale);
      };
      // return
      return cache[locale];
    });
  };

  // retrieve a locale
  module.exports = function(locale) {
    return get(locale);
  };

  // express plugin
  module.exports.express = function(req, res, next) {
    var e, i18n;
    try {
      i18n = get(req.locale);
      req.i18n = res.locals.i18n = i18n;
      return next();
    } catch (error1) {
      e = error1;
      return next(e);
    }
  };

  // helpers
  locale = module.exports.locale = function(language, country) {
    if (country != null) {
      return [language, country].join('-');
    } else {
      return language;
    }
  };

  language = module.exports.language = function(locale) {
    return locale.split('-')[0];
  };

  country = module.exports.country = function(locale) {
    return locale.split('-')[1];
  };

  // export shortcuts
  languages = module.exports.languages = _.keys(serverConfig.locale.languages);

  countries = module.exports.countries = serverConfig.locale.countries;

  // list of officially supported locale combinations
  locales = module.exports.locales = [];

  _.each(serverConfig.locale.languages, function(countries, language) {
    return _.each(countries, function(country) {
      return locales.push(locale(language, country));
    });
  });

  // initial load
  load();

}).call(this);
