// Generated by CoffeeScript 2.4.1
(function() {
  var Configuration, _, _s, deepExtend, fs, path, stripJsonComments;

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  // modules
  _ = require('underscore');

  _s = require('underscore.string');

  fs = require('fs');

  path = require('path');

  stripJsonComments = require('strip-json-comments');

  // deep extending
  deepExtend = require('elib/tools/deepExtend');

  // exports class
  module.exports = Configuration = class Configuration {
    // load configuration
    load(dir) {
      var config;
      // read available file
      config = {};
      _.each(fs.readdirSync(dir), (file) => {
        var content, e, flavor, name, parts;
        if (_s.endsWith(file, 'json')) {
          // extract name
          parts = file.split('.');
          name = parts.shift();
          flavor = parts.shift();
          if (flavor !== 'default') {
            flavor = 'override';
          }
          try {
            // load the content
            // try to load content
            content = fs.readFileSync(path.join(dir, file), 'utf8');
            content = stripJsonComments(content);
            if (!_.has(config, name)) {
              // set config
              config[name] = {};
            }
            // parse data
            return config[name][flavor] = JSON.parse(content);
          } catch (error) {
            e = error;
            console.error('Unable to load configuration ' + file);
            return console.error(e);
          }
        }
      });
      // loop namespaces
      _.each(config, (values, namespace) => {
        if (_.has(values, 'default')) {
          if (_.has(values, 'override')) {
            return this[namespace] = deepExtend(values.default, values.override);
          } else {
            return this[namespace] = values.default;
          }
        } else {
          return this[namespace] = values.override;
        }
      });
      // merge default namespace
      if (_.has(this, 'default')) {
        _.each(this['default'], (value, key) => {
          return this[key] = value;
        });
        return delete this['default'];
      }
    }

  };

}).call(this);
