// Generated by CoffeeScript 2.4.1
(function() {
  var path, rqf;

  rqf = require('rqf');

  path = require('path');

  // set base path
  rqf.base = rqf.dir(path.normalize(path.join(__dirname, '..')));

}).call(this);
