// Generated by CoffeeScript 2.4.1
(function() {
  var exit;

  process.env.NODE_ENV = process.env.NODE_ENV || 'test';

  global.TEST_ENV = process.env.TEST_ENV != null ? process.env.TEST_ENV.split(' ') : [];

  exit = process.exit;

  process.exit = function(code) {
    return setTimeout(function() {
      return exit();
    }, 200);
  };

  require('../node_modules/mocha/bin/_mocha');

}).call(this);
