// Generated by CoffeeScript 2.4.1
(function() {
  // libraries
  var _, i18n, rqf, serverConfig;

  _ = require('underscore');

  rqf = require('rqf');

  // configuration
  serverConfig = rqf('server.config');

  // i18n
  i18n = require('elib/i18n');

  // export
  module.exports.assemble = function(locale, segments, params) {
    var querystring, translation, url;
    // query string module
    querystring = require('querystring');
    // i18n
    translation = i18n(locale);
    // init url
    url = [];
    // first segment is always the language
    url.push(i18n.language(locale));
    // assemble url
    _.each(segments, function(segment) {
      if (segment.indexOf('_') >= 0) {
        return url.push(translation.translate(segment).fetch());
      } else {
        return url.push(segment);
      }
    });
    // join
    url = url.join('/');
    if (_.size(params) > 0) {
      // add params
      url += '?' + querystring.stringify(params);
    }
    // return
    return url;
  };

  // create an absolute url based on protocol, host, locale and path
  module.exports.absolute = function(protocol, host, path = '/') {
    var url;
    // url module
    url = require('url');
    if (path[0] !== '/') {
      // leading slash
      path = '/' + path;
    }
    // default site
    return url.format({
      protocol: protocol,
      host: host
    }) + path;
  };

}).call(this);
