// Generated by CoffeeScript 2.4.1
(function() {
  var _, _s, error, jsonApi;

  _ = require('underscore');

  _s = require('underscore.string');

  error = require('elib/error');

  jsonApi = require('elib/tools/jsonApi');

  // module export
  module.exports = function(options = {}) {
    var appendFilters, appendOption, getValues, parseAttribute;
    // init options
    if (options.relations == null) {
      options.relations = {};
    }
    if (options.mappings == null) {
      options.mappings = {};
    }
    if (options.typeIndex == null) {
      options.typeIndex = 1;
    }
    getValues = function(value, mapFunction) {
      var result;
      // this is only to parse the values
      // and if supplied a mapFunction
      // we should apply it to the results
      result = value;
      if (!_.isArray(result)) {
        result = result != null ? result.split(',').map(decodeURIComponent) : void 0;
      }
      if (mapFunction && result) {
        result = result.map(mapFunction);
      }
      return result;
    };
    parseAttribute = function(attr, mainType, mapFunction) {
      var i, item, key, len, result, val;
      if (!attr) {
        return;
      }
      result = {};
      if (_.isArray(attr)) {
        for (i = 0, len = attr.length; i < len; i++) {
          item = attr[i];
          result = _.extend(result, parseAttribute(item, mainType, mapFunction));
        }
      } else if (_.isObject(attr)) {
        for (key in attr) {
          val = attr[key];
          if (val === true) {
            result = _.extend(result, parseAttribute(key, mainType, mapFunction));
          } else {
            result[key] = getValues(val, mapFunction);
          }
        }
      } else {
        result[mainType] = getValues(attr, mapFunction);
      }
      return result;
    };
    appendOption = function(mainOptions, parsedOption, fieldName) {
      var results, type, value;
      results = [];
      for (type in parsedOption) {
        value = parsedOption[type];
        if (!mainOptions[type]) {
          mainOptions[type] = {};
        }
        results.push(mainOptions[type][fieldName] = value);
      }
      return results;
    };
    appendFilters = function(queryOptions, type, filters) {
      var key, value;
      if (!queryOptions[type]) {
        queryOptions[type] = {};
      }
      if (!queryOptions[type].filters) {
        queryOptions[type].filters = {};
      }
      for (key in filters) {
        value = filters[key];
        //create 'contains in' filter
        if (_.isArray(value)) {
          queryOptions[type].filters[key] = {
            in: value
          };
          delete filters[key];
        //break the filters by type
        } else if (_.isObject(value)) {
          // map >, >=, <, <=
          _.each(_.keys(value), function(k) {
            if (k !== 'gt' && k !== 'gte' && k !== 'lt' && k !== 'lte') {
              return;
            }
            if (queryOptions[type].filters[key] == null) {
              queryOptions[type].filters[key] = {};
            }
            queryOptions[type].filters[key]['$' + k] = value[k];
            return delete value[k];
          });
          if (!_.isEmpty(value)) {
            // append filters if not empty value
            appendFilters(queryOptions, key, value);
          }
          delete filters[key];
        }
      }
      return queryOptions[type].filters = _.extend(queryOptions[type].filters, filters);
    };
    return {
      // exported methods
      parseAttributes: function(req, res, next) {
        var filters, queryOptions, ref, sorts, type;
        // we might be able to figure out the type only if
        // the route is defined and passed to the express router
        type = (ref = req.route) != null ? ref.split('/')[options.typeIndex] : void 0;
        sorts = parseAttribute(req.query.sort, type, function(sort) {
          if (_s.startsWith(sort, '-')) {
            // then this is desc
            return [sort.slice(1), 'DESC'];
          } else {
            return [sort, 'ASC'];
          }
        });
        queryOptions = {};
        // parse all the request options
        appendOption(queryOptions, parseAttribute(req.query.fields, type), 'fields');
        appendOption(queryOptions, parseAttribute(req.query.include, type), 'includes');
        appendOption(queryOptions, parseAttribute(req.query.templates, type), 'templates');
        appendOption(queryOptions, parseAttribute(req.query.limit, type), 'limit');
        appendOption(queryOptions, parseAttribute(req.query.offset, type), 'offset');
        appendOption(queryOptions, sorts, 'sorts');
        filters = _.clone(req.query);
        // after removing the parsed options we should only have the query left
        delete filters.fields;
        delete filters.include;
        delete filters.sort;
        delete filters.templates;
        delete filters.limit;
        delete filters.offset;
        if (_.isEmpty(filters)) {
          filters = void 0;
        }
        if (filters != null) {
          appendFilters(queryOptions, type, filters);
        }
        // new limeApi
        req.limeApi = _.clone(queryOptions);
        req.limeApi.type = type;
        if (req.user) {
          // old jsonApiAttributes
          queryOptions.user = req.user;
        }
        queryOptions.institution_id = req.institution_id;
        req.jsonApiAttributes = queryOptions;
        req.jsonApiAttributes.type = type;
        return next();
      },
      // Exported methods
      parseBody: function(req, res, next) {
        var data, el, element, elements, i, isArray, key, len, mapping, ref, relationType, relations, value;
        if (req.limeApi == null) {
          // lime api unavailable?
          throw new Error('please parse attributes before body');
        }
        // body?
        if (req.body != null) {
          // data attribute?
          if (req.body.data != null) {
            // get data
            data = req.body.data;
            isArray = _.isArray(data);
            if (!isArray) {
              // wrap
              data = [data];
            }
            elements = [];
// loop
            for (i = 0, len = data.length; i < len; i++) {
              element = data[i];
              // verify type - impossible right now because of resource-less api style
              //throw new error.InvalidArgument("body data type #{element.type} differs from api type #{req.limeApi.type}") unless element.type is req.limeApi.type

              // set body
              el = element.attributes || {};
              if (element.id != null) {
                el.id = element.id;
              } else {
                if (el.id != null) {
                  delete el.id;
                }
              }
              // resolve (and remove) relationships
              if (element.relationships != null) {
                // get relations
                relations = options.relations[element.type] || {};
                ref = element.relationships;
                // loop relationships
                for (key in ref) {
                  value = ref[key];
                  // is it specified?
                  if (relations[key] != null) {
                    relationType = relations[key];
                    if (_.isObject(relationType)) {
                      mapping = relationType.mapping;
                      relationType = relationType.type;
                    } else {
                      mapping = options.mappings[relationType];
                    }
                    // verify mapping
                    //throw new error.InvalidArgument("relationship of type #{relationType} differs from #{value.data.type} for #{key}") unless relationType is value.data.type

                    // array or not
                    if (value.data == null) {
                      el[mapping] = null;
                    } else if (_.isArray(value.data)) {
                      el[mapping] = _.map(value.data, function(d) {
                        return d.id;
                      });
                    } else {
                      // store mapping
                      if (value.data) { //seems that ember-data does not omit empty reltion, but passes it as null
                        el[mapping] = value.data.id;
                      }
                    }
                  }
                }
              }
              if (_.size(el) === 1 && (el.id != null)) {
                // only an id?
                el = el.id;
              }
              // push
              elements.push(el);
            }
            if (!isArray) {
              // unwrap and set
              elements = _.first(elements);
            }
            req.limeApi.body = elements;
          } else {
            // fallback to traditional body
            req.limeApi.body = req.body;
          }
        }
        // proceed
        return next();
      },
      parseIds: function(req, res, next, reqIds, paramName) {
        var ids, ref, ref1, type;
        type = (ref = req.route) != null ? (ref1 = ref.path) != null ? ref1.split('/')[1] : void 0 : void 0;
        req.jsonApiAttributes[type] = req.jsonApiAttributes[type] || {};
        req.limeApi[type] = req.limeApi[type] || {};
        // here we will get the ids from the req.params because probably the hashids
        // middleware has hashed the ids and put them there
        ids = req.params[paramName];
        if (!_.isArray(ids)) {
          ids = [ids];
          // http://jsonapi.org/format/#fetching-resources-responses-200
          // A server MUST respond to a successful request to fetch an individual resource with a resource object
          // or null provided as the response document's primary data.
          req.jsonApiAttributes[type].individualResource = true;
        }
        if (req.jsonApiAttributes[type].filters) {
          req.jsonApiAttributes[type].filters.id = {
            in: ids
          };
        } else {
          req.jsonApiAttributes[type].filters = {
            id: {
              in: ids
            }
          };
        }
        if (req.limeApi[type].filters) {
          req.limeApi[type].filters.id = {
            in: ids
          };
        } else {
          req.limeApi[type].filters = {
            id: {
              in: ids
            }
          };
        }
        return next();
      },
      errors: function(err, req, res, next) {
        var code, details, errors, httpCode, i, key, len, ref, title;
        // initialize
        httpCode = 500;
        errors = [];
        if (!_.isArray(err)) {
          // wrap in array
          err = [err];
        }
// loop errors
        for (key = i = 0, len = err.length; i < len; key = ++i) {
          error = err[key];
          // init error with code
          code = 500;
          title = 'Internal server error';
          // error name given?
          if (error.name != null) {
            if (error.name === 'PermissionDenied') {
              code = 403;
              title = 'This operation is forbidden';
            } else if (error.name === 'Unauthorized') {
              code = 401;
              title = 'Please authorize yourself';
            } else if (error.name === 'ObjectNotFound') {
              code = 404;
              title = 'Not Found';
            } else if (error.name === 'SequelizeUniqueConstraintError') {
              code = 409;
              title = 'Conflict';
            } else if ((ref = error.name) === 'InvalidState' || ref === 'InvalidArgument') {
              code = 400;
              title = 'Bad Request';
            } else if (error.name === 'NoContent') {
              code = 204;
              title = 'No Content';
            } else if (error.name === 'NotImplemented') {
              code = 501;
              title = 'This is not implemented yet';
            // cleaning up the OAuth2Errors
            } else if (error.name === 'OAuth2Error' && error.error === 'invalid_request') {
              code = 401;
              title = 'Please authorize yourself';
            } else if (error.name === 'OAuth2Error' && error.error === 'wrong_credentials') {
              code = 401;
            }
          }
          if ((error.message != null) && error.message !== '') {
            // set title
            title = error.message;
          }
          // error details given
          details = {};
          if (error.details != null) {
            details = _.pick(error.details, ['id', 'title', 'detail', 'status', 'source', 'meta']);
          }
          // push error
          errors.push(_.extend({
            title: title,
            status: code
          }, details));
          if (key === 0) {
            // set httpCode
            httpCode = code;
          }
        }
        // send response
        res.set('Content-Type', 'application/vnd.api+json');
        res.statusCode = httpCode;
        return res.send({
          jsonapi: {
            version: "1.0"
          },
          errors: errors
        });
      }
    };
  };

}).call(this);
