// Generated by CoffeeScript 2.4.1
(function() {
  var _, _s, deepExtend, res;

  _ = require('underscore');

  _s = require('underscore.string');

  res = require('express').response;

  deepExtend = require('elib/tools/deepExtend');

  module.exports = function(options = {}) {
    var addResourceRelationship, deduplicateIncluded, hashids, parseIncluded, parseResourceRecursive, parseResources, resourceToJson;
    // init options
    if (options.relations == null) {
      options.relations = {};
    }
    if (options.mappings == null) {
      options.mappings = {};
    }
    // initialize hashids
    hashids = require('elib/tools/hashids')(options);
    addResourceRelationship = function(resource, reference, type, id, isArray) {
      var base, value;
      // make sure relationships is there
      if (resource.relationships == null) {
        resource.relationships = {};
      }
      // the relationship value
      value = {
        type: type,
        id: id
      };
      if (id == null) {
        value = null;
      }
      // is it an array?
      if (isArray) {
        if ((base = resource.relationships)[reference] == null) {
          base[reference] = {
            data: []
          };
        }
        return resource.relationships[reference].data.push(value);
      } else {
        return resource.relationships[reference] = {
          data: value
        };
      }
    };
    parseIncluded = function(resource, reference, includedResource, includeType, included, isArray) {
      var result;
      // really a resource or only an id?
      if (_.isObject(includedResource)) {
        // call our parseResource again to make sure we are parsing all the included resources
        result = parseResourceRecursive(includedResource, includeType, included);
        if ((included[includeType] != null) && Array.isArray(included[includeType])) {
          included[includeType].push(result);
        } else {
          included[includeType] = [result];
        }
        // parse links
        return addResourceRelationship(resource, reference, result.type, result.id, isArray);
      } else {
        return addResourceRelationship(resource, reference, includeType, hashids.hash(includedResource, includeType), isArray);
      }
    };
    parseResourceRecursive = function(resource, type, included, aggregated = false) {
      var hashed, i, item, key, len, relationName, relationType, relations, result, value;
      result = {
        id: null,
        type: type,
        attributes: {}
      };
      if (options.relations[type] != null) {
        relations = options.relations[type];
      }
      for (key in resource) {
        value = resource[key];
        // defined relation?
        if ((relations != null ? relations[key] : void 0) != null) {
          // fetch relation type
          relationType = _.isObject(relations[key]) ? relations[key]['type'] : relations[key];
          // if the value is an array, we want to parse all of its elements
          if (_.isArray(value)) {
            for (i = 0, len = value.length; i < len; i++) {
              item = value[i];
              parseIncluded(result, key, item, relationType, included, true);
            }
          } else {
            parseIncluded(result, key, value, relationType, included, false);
          }
        } else if (key === 'id') { // hash type key?
          result[key] = hashids.hash(value, type);
          if (aggregated) {
            result[key] = '-' + result[key] + '-';
          }
        } else if (_s.endsWith(key, '_id') && resource[`${key.slice(0, -3)}_type`]) {
          // generic type based mapping (e.g. remote_id / remote_type)
          relationType = _.findKey(options.mappings, function(item) {
            return item === resource[`${key.slice(0, -3)}_type`] + '_id';
          });
          // generic link found
          if (relationType != null) {
            result.attributes[key] = hashids.hash(value, relationType);
          } else {
            result.attributes[key] = value;
          }
        } else {
          // figure out link type
          relationType = _.findKey(options.mappings, function(item) {
            return item === key;
          });
          // figure out relations type
          relationName = _.findKey(relations, function(item) {
            if (_.isObject(item)) {
              return item.mapping === key;
            } else if (_.has(options.mappings, item)) {
              return options.mappings[item] === key;
            } else {
              return false;
            }
          });
          // relationName found but no linkType
          if ((relationName != null) && (relationType == null)) {
            relationType = _.isObject(relations[relationName]) ? relations[relationName]['type'] : relations[relationName];
          }
          // both link and relation type found?
          if ((relationType != null) && (relationName != null)) {
            // hashed value
            hashed = hashids.hash(value, relationType);
            // add resource link
            result.attributes[key] = hashed;
            if (value === 0) {
              // add resource link
              hashed = null;
            }
            addResourceRelationship(result, relationName, relationType, hashed, false);
          } else if (relationType != null) {
            result.attributes[key] = hashids.hash(value, relationType);
          } else {
            result.attributes[key] = value;
          }
        }
      }
      if (!(_.size(result.attributes) > 0)) {
        // return the new resource
        delete result.attributes;
      }
      return result;
    };
    deduplicateIncluded = function(included) {
      var deduplicated, i, ids, key, len, value, values;
      // this basically makes sure we are not sending the same included element twice
      deduplicated = [];
      for (key in included) {
        values = included[key];
        ids = {};
        for (i = 0, len = values.length; i < len; i++) {
          value = values[i];
          if (!(value.id in ids)) {
            ids[value.id] = value;
          } else {
            ids[value.id] = deepExtend(ids[value.id], value);
          }
        }
        deduplicated = deduplicated.concat(_.values(ids));
      }
      /*
          The logic below is ready to be used, what's left is a confirmation
          if it's needed or not, what it basically does is that it makes sure
          the included elements are at least sorted by the first entry in the sorts
          jsonApiAttribute of a type.
          The included elements might be elements gathered by sub-queries which means the ORDER BY query
          didn't cover all of them but only parts them.
      */
      // # since included are deduplicated now, let's check if we need to sort
      // # this included array
      // if jsonApiAttributes[key]?.sorts?.length > 0 and deduplicatedLinked[key].length > 1
      //     sorts = jsonApiAttributes[key].sorts
      //     # since we cannot handle combined sorts at this point
      //     # we will be only sorting on the first element in the sort array
      //     deduplicatedLinked[key] = _.sortBy deduplicatedLinked[key], (o) -> o[sorts[0][0]]
      //     # we still need to check if the sort is descending then we need to reverse the array
      //     if sorts[0][1] is 'DESC'
      //         deduplicatedLinked[key].reverse()
      return deduplicated;
    };
    parseResources = function(resources, type) {
      var aggregated, i, len, resource, result;
      // is it an array?
      result = {
        data: null,
        included: {}
      };
      if (Array.isArray(resources)) {
        // loop resources
        result.data = [];
        for (i = 0, len = resources.length; i < len; i++) {
          resource = resources[i];
          aggregated = ((resource != null ? resource.aggregated : void 0) != null) && resource.aggregated;
          resource = resourceToJson(resource);
          result.data.push(parseResourceRecursive(resource, type, result.included, aggregated));
        }
      } else if (resources === null) { //individualResource special case
        result.data = null;
      } else {
        aggregated = ((resource != null ? resource.aggregated : void 0) != null) && resource.aggregated;
        resources = resourceToJson(resources);
        result.data = parseResourceRecursive(resources, type, result.included, aggregated);
      }
      // finalize included
      if (_.size(result.included) > 0) {
        result.included = deduplicateIncluded(result.included);
      } else {
        delete result.included;
      }
      // return
      return result;
    };
    resourceToJson = function(resource) {
      if (resource.getPlain != null) {
        return resource.getPlain();
      } else if (resource.toJSON != null) {
        return resource.toJSON();
      } else {
        return JSON.parse(JSON.stringify(resource));
      }
    };
    // register and return send method
    return res.jsonApiSend = res.limeSend = function(resources, meta) {
      var individualResource, ref;
      if (!resources) {
        this.statusCode = 204;
        return this.send();
      } else {
        // http://jsonapi.org/format/#fetching-resources-responses-200
        // A server MUST respond to a successful request to fetch an individual resource with a resource object
        // or null provided as the response document's primary data.
        individualResource = (ref = this.req.jsonApiAttributes[this.req.jsonApiAttributes.type]) != null ? ref.individualResource : void 0;
        if (individualResource) {
          resources = (function() {
            switch (resources.length) {
              case 0:
                return null;
              case 1:
                return resources[0];
              default:
                return resources;
            }
          })();
        }
        this.set('Content-Type', 'application/vnd.api+json');
        meta = meta != null ? {
          meta: meta
        } : {};
        return this.send(_.extend({
          jsonapi: {
            version: "1.0"
          }
        }, parseResources(resources, this.req.jsonApiAttributes.type), meta));
      }
    };
  };

}).call(this);
